##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## to make project
##

all:
	@make --no-print-directory -C sdl
	@make --no-print-directory -C ncurses
	@make --no-print-directory -C sfml

clean:
	@make clean  --no-print-directory -C sdl
	@make clean  --no-print-directory -C ncurses
	@make clean  --no-print-directory -C sfml

fclean:
	@make fclean  --no-print-directory -C sdl
	@make fclean  --no-print-directory -C ncurses
	@make fclean  --no-print-directory -C sfml

re:
	@make re  --no-print-directory -C sdl
	@make re  --no-print-directory -C ncurses
	@make re  --no-print-directory -C sfml