##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## to make project
##

all:
	@make --no-print-directory -C pacman
	@make --no-print-directory -C nibbler

clean:
	@make clean  --no-print-directory -C pacman
	@make clean  --no-print-directory -C nibbler

fclean:
	@make fclean  --no-print-directory -C pacman
	@make fclean  --no-print-directory -C nibbler

re:
	@make re  --no-print-directory -C pacman
	@make re  --no-print-directory -C nibbler